### ISSUE TITLE
[Bug] TPS

### ISSUE THREAD

**Issue by Krimatoria** [northwesttrees-gaming/CCTVCraft-Forge#34]
### Current Behavior

![image](https://github.com/northwesttrees-gaming/CCTV-Craft/assets/106809386/72e1462a-378c-43e8-85e8-432ac36f67cb)

### Mod Build

CCTV Craft 4.6.2 for 1.19.2

### Minecraft Release

Minecraft 1.19.2
Forge 43.3.5

**Comment by northwesttreesgaming** [comment]
I just found this out today actually, I noticed concel said something like 200 ticks behind. CCTV Craft 4 is sadly not possible to fix this issue  but I have been working on a fith version, just started it today actually that will allow more flexibility and hopefully improve performance. I am still early in testing but I am hoping that this will resolve this issue when the core mod is released.

**Comment by Krimatoria** [comment]
> На самом деле я узнал об этом только сегодня, я заметил, что Консел сказал, что отставание примерно на 200 тиков. К сожалению, в CCTV Craft 4 невозможно решить эту проблему, но я работаю над фит-версией, на самом деле только сегодня начал ее, которая обеспечит большую гибкость и, надеюсь, улучшит производительность. Я все еще на ранней стадии тестирования, но надеюсь, что это решит эту проблему, когда будет выпущен основной мод.

Oh, if there is a version for the test, I will be glad) maybe you have a Discord?

**Comment by northwesttreesgaming** [comment]
Sadly it's just the way I went about setting up the mod, many things use procedures for World Tick Update and Player Tick Update my best guess is it is caused as I developed the mod. Running it through functions and tagging the function as tick seems to have kept the TPS down so I will need to remake the mod. The downside is it will most likely be for NeoForge when it does come out as MCreator will be updating soon to that API and dropping Forge support so I won't have much option but to migrate to NeoForge when I make the improvements.

**Comment by Krimatoria** [comment]
> MCreator

That is, many mods will have to be updated for NEO at 1.20.4, since they simply cannot update mods on Forge if they update Mcreate? I just don't know how to create mods. 

- Added base support for Net Forge 1.20.4 
MCreate wrote in an update that he has already added support.

**Comment by northwesttreesgaming** [comment]
MCreator has it done I think but it's in a snapshot testing stage, so it's not officially released yet but it will be when 2024.1 is released.

When it comes to MCreator we can easily port our mods over to a new generator which takes little to no time to do. When I tested the snapshot converting from Forge to NeoForge took a few minutes to convert all the elements over but I figure it will be less once its all on the same platform.

For people developing on newer versions of MCreator they will be making mods on NeoForge I think there are older downloads stashed somewhere on the MCreator downloads page but I plan to keep this version installed under a separate folder until I have the CCTVCraft done. I make tutorials for the program every week so I need both versions at least when its released until I am done with wrapping stuff up.

I will also be trying to migrate some of the script over to functions I read that functions are more efficient than command blocks which I don't use but Wiki says it can help with performance so I will see if I can migrate most of the update tick script for player and world over to command format in hopes this will reduce the demand.

I will be focusing on #33 for 4.8.0 and 4.9.0 then 4.10 and 4.11 will focus on possible optimizations for TPS. This way I have a bit more time to try to resolve some of the issues.

I have tested the camera view on the NeoForge workspace already and it is possible to convert it to function but it just takes a lot more time to work out some of these commands than the procedure script. I may be able to run the script directly but I need to know what commands I need which is mostly just trial and error.

So that's the plan at least, no clue about a set date, updating the tags for #33 is taking some time to do as I need to research the tags and then update the recipes. But most of the things in the feedback are done just need to manage recipes and tags pretty much.

**Comment by Krimatoria** [comment]
> Я думаю, что MCreator уже сделал это, но он находится на стадии тестирования моментальных снимков, поэтому официально он еще не выпущен, но это произойдет, когда выйдет 2024.1.
> 
> Когда дело доходит до MCreator, мы можем легко перенести наши моды на новый генератор, что не требует много времени. Когда я тестировал преобразование снимков из Forge в NeoForge, преобразование всех элементов заняло несколько минут, но я полагаю, что этого будет меньше, если все они будут на одной платформе.
> 
> Для людей, разрабатывающих более новые версии MCreator, они будут создавать моды на NeoForge. Я думаю, что где-то на странице загрузок MCreator спрятаны старые загрузки, но я планирую хранить эту версию в отдельной папке, пока не закончу CCTVCraft. Я делаю учебные пособия по программе каждую неделю, поэтому мне нужны обе версии, по крайней мере, после ее выпуска, пока я не закончу с завершением работы.
> 
> Я также попытаюсь перенести часть скрипта на функции. Я читал, что функции более эффективны, чем командные блоки, которые я не использую, но Wiki говорит, что это может помочь с производительностью, поэтому я посмотрю, смогу ли я перенести большую часть обновлений. тик-скрипт для игрока и всего мира в командном формате в надежде, что это снизит спрос.
> 
> Я сосредоточусь на [№ 33](https://github.com/northwesttrees-gaming/CCTVCraft-Forge/issues/33) для 4.8.0 и 4.9.0, а затем в 4.10 и 4.11 сосредоточусь на возможных оптимизациях для TPS. Таким образом, у меня будет немного больше времени, чтобы попытаться решить некоторые проблемы.
> 
> Я уже протестировал вид камеры в рабочей среде NeoForge, и его можно преобразовать в функцию, но на отработку некоторых из этих команд уходит гораздо больше времени, чем на сценарий процедуры. Возможно, я смогу запустить сценарий напрямую, но мне нужно знать, какие команды мне нужны, а это в основном метод проб и ошибок.
> 
> По крайней мере, таков план: понятия не имею о установленной дате, обновление тегов для [№ 33](https://github.com/northwesttrees-gaming/CCTVCraft-Forge/issues/33) занимает некоторое время, так как мне нужно изучить теги, а затем обновить рецепты. Но большинство вещей в отзывах уже сделаны, просто нужно в значительной степени управлять рецептами и тегами.

It's a pity I don't know English well. Oh, I would write one mod that I really dream of getting for just one item in the game from the Alien Isolation universe. Since no one has made an analogue yet..but I can't program from the word at all) I can only generate ideas)

**Comment by Krimatoria** [comment]
> Я думаю, что MCreator уже это сделал, но он находится на стадии тестирования моментальных кадров, поэтому официально он еще не выпущен, но это произойдет, когда выйдет 2024.1.
> 
> Когда дело дойдет до MCreator, мы можем легко перенести нашу моду на новый генератор, который не требует много времени. Когда я тестировал преобразование кадров из Forge в NeoForge, преобразование всех элементов платформы заняло несколько минут, но я сказал, что этого будет меньше, если все они будут на одной.
> 
> Для людей, разрабатывающих более новую версию MCreator, они создают моду на NeoForge. Я думаю, что где-то на странице загрузок MCreator спрятаны старые загрузки, но я планирую хранить эту версию в отдельной версии, пока не закончу CCTVCraft. Я делаю технические средства по программе каждую неделю, поэтому мне нужны обе версии, по крайней мере, после ее выпуска, пока я не закончу с завершением работы.
> 
> Я также применяю перенос части скрипта на функцию. Я читал, что функция более эффективна, чем командные блоки, которые я не использую, но Wiki говорит, что это может помочь с производительностью, поэтому я посмотрю, если я смогу перенести часть обновлений. тик-скрипт для игроков и всего мира в командном формате в надежде, что это снизит спрос.
> 
> Я сосредоточусь на [№ 33](https://github.com/northwesttrees-gaming/CCTVCraft-Forge/issues/33) для 4.8.0 и 4.9.0, а затем на 4.10 и 4.11 сосредоточусь на возможных оптимизациях для TPS. Таким образом, у меня будет немного больше времени, чтобы обвиняемые решили некоторые проблемы.
> 
> Я уже протестировал вид камеры в рабочей среде NeoForge, и его можно перевести в режим, но на отработку некоторых из этой команды ушло гораздо больше времени, чем предусмотрено процедурами сценария. Возможно, я запущу сценарий напрямую, но мне нужно знать, какие команды мне нужны, и это в основном метод проб и ошибок.
> 
> На самом деле, такой план: понятия не об установленной дате, обновление тегов для [№ 33](https://github.com/northwesttrees-gaming/CCTVCraft-Forge/issues/33) занимает некоторое время, так как мне нужно изучить теги, а затем обновить рецепты. Но большинство вещей в отзывах уже сделаны, просто нужно иметь достаточно ресурсов для управления рецептами и тегами.

Probably writing mods is cool) I wish you good luck)

**Comment by northwesttreesgaming** [comment]
Chances are this mod is too large for Forge to narrow down the exact cause.
I would need to design it better from day one to find the cause.
I did not know about the TPS F3 screen until this post or I would have had a better eye on it when I was making the mod.
But I will make sure that I keep the TPS monitored on the NeoForge version once I start working on the remake for it.
