### ISSUE TITLE
question about drone

### ISSUE THREAD

**Issue by nyrvalyx** [northwesttrees-gaming/CCTVCraft-Forge#41]
I play on version 4.7.0, and I would like to use the drone but I don't know how, I put it on the drone station, connected a voltage panel to it, charged it to the max, connected a controller to it and I don't know how to fly, when he used "use" with that joystick, I enter the drone and x exits, but when I try to move by clicking "w, a, s, d" it says that the drone is blocked, how do I turn it off?

**Comment by northwesttreesgaming** [comment]
This was a problem introduced in 1.19.2 or 1.19.4 when Mojang removed support for testing materials.
I did not know about them dropping support for it until after I released 1.20.1 for this mod so it's been a problem with the drones for controls for some time. On my test branch I have fixed drones and tested them but not sure when I will be able to find the time to finish testing the rest of the mod, I know monitors have major issues still one with the substring for sure so I need to fix that and most likely some other issues with the mod. I have been having to test all features which is taking the most time, and then narrowing down the procedure with the issue is even harder as procedures that used the material block don't produce a error so I have no way to know what exact procedure is causing the problem.

I have been taking a small break but will be working on it soon.
I did get the drone testing all done and made several fixes. But other parts of the mod still need testing and fixing.

If you find any other problems with devices you can report them here and it will help me narrow down the issues for sure.
When the version is ready I can port it to 1.19.4 and 1.20.1.

**Comment by northwesttreesgaming** [comment]
Related to this issue #35
